var session;

module.exports = {
  'Create Client': function (browser) {
    session = browser;
    session
      .resizeWindow(1500, 1000)
      .url('http://localhost:8080/register')
      .waitForElementVisible('body', 1000)
      .setValue('input[name="first_name"]', 'Test')
      .setValue('input[name="last_name"]', 'Client')
      .setValue('input[name="username"]', 'test@client.com')
      .setValue('input[name="password"]', 'testpw')
      .waitForElementVisible('button[type="submit"]', 1000)
      .click('button[type="submit"]')
      .pause(1000)
      .click('[href="#users"]')
      .pause(500)
      .click('i[class="material-icons"]')
      .pause(300)
      .click('label[for="is_student"]')
      .pause(500)
      .click('input[type="submit"]')
      .pause(500)
      .click('tr td a')
      .pause(500)
      .setValue('input', '200')
      .pause(200)
      .click('button[class="btn btn-primary false"]')
      .pause(1000)
      .keys('4242')
      .pause(100)
      .keys('4242')
      .pause(100)
      .keys('4242')
      .pause(100)
      .keys('4242')
      .pause(500)
      .keys('\uE004')
      .pause(500)
      .keys('11')
      .keys('2020')
      .pause(500)
      .keys('\uE004')
      .pause(500)
      .keys('123')
      .pause(500)
      .keys('\uE004')
      .pause(500)
      .keys('77777')
      .pause(500)
      .keys('\uE007')
      .pause(5000)
      // Pause may need to be longer on other test clients

      // Test for making a new location
      .click('[href="#users"]')
      .pause(500)
      .click('i[class="material-icons"]')
      .pause(300)
      .click('label[for="is_admin"]')
      .pause(500)
      .click('input[type="submit"]')
      .pause(500)
      .click('[href="#locations"]')
      .pause(1000)
      .click('a[class="waves-effect waves-teal btn modal-trigger"]')
      .pause(500)
      .click('input[id="name"]')
      .keys('420 Central')
      .keys('\uE004')
      .keys('420')
      .keys('\uE004')
      .keys('420')
      .keys('\uE004')
      .keys('420')
      .keys('\uE004')
      .keys('420')
      .keys('\uE004')
      .keys('Texas')
      .keys('\uE004')
      .keys('420')
      .pause(100)
      .click('input[type="submit"]')
      .pause(1000)

      // Test for creating a term


      .pause(2000)

      .end();
  }
}
